version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/Lingarr.Client"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"

  # Backend dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      nuget-major:
        update-types:
          - "major"
